/**
 * pythonDebug.ts — Launch Markdown Python cells under VS Code's debugger.
 *
 * Rat's normal execution path sends cells to a rat runtime.  This module is a
 * separate, explicit path for the common debugging workflow: keep breakpoints in
 * the project/library source, execute one or more Markdown Python cells in a
 * normal debugpy launch, and let VS Code stop if those breakpoints are hit.
 */

import * as fs from "fs";
import * as path from "path";
import * as vscode from "vscode";
import {
  cellAtLine,
  parseCells,
  type CodeCell,
} from "./cells";
import { ratResolve, type ResolvedRuntimeInfo } from "./rat";
import { resolveRuntime } from "./resolve";

export type PythonDebugTarget = "cell" | "above";

interface RunnerInfo {
  path: string;
  code: string;
  cwd: string;
  env: Record<string, string>;
  python?: string;
}

/** Debug the Python cell at `line`, or all Python cells up to it. */
export async function debugPythonCellsAtLine(
  ctx: vscode.ExtensionContext,
  editor: vscode.TextEditor,
  line: number,
  target: PythonDebugTarget,
): Promise<void> {
  const document = editor.document;
  const cells = parseCells(document);
  const current = cellAtLine(cells, line) ?? cells.find((cell) => cell.openLine === line);

  if (!current?.executable || current.ratLang !== "py") {
    vscode.window.showInformationMessage("No executable Python cell at cursor");
    return;
  }

  const selected = target === "above"
    ? cells.filter((cell) => cell.executable && cell.ratLang === "py" && cell.openLine <= current.openLine)
    : [current];

  const runnable = selected.filter((cell) => cell.code.trim().length > 0);
  if (runnable.length === 0) {
    vscode.window.showInformationMessage("Python cell is empty");
    return;
  }

  const runner = await createRunner(ctx, document, runnable, target);
  await launchRunner(document, runner, target, runnable.length);
}

async function createRunner(
  ctx: vscode.ExtensionContext,
  document: vscode.TextDocument,
  cells: CodeCell[],
  target: PythonDebugTarget,
): Promise<RunnerInfo> {
  const initialCwd = workspaceCwd(document);
  const ratRuntime = await resolveRatPythonRuntime(document, initialCwd);
  const cwd = ratRuntime?.cwd || initialCwd;
  const dir = path.join(ctx.globalStorageUri.fsPath, "python-debug");
  await fs.promises.mkdir(dir, { recursive: true });

  const base = slug(path.basename(document.fileName, path.extname(document.fileName)) || "notebook");
  const file = path.join(
    dir,
    `${base}-${target}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}.py`,
  );

  const code = buildRunnerCode(document, cells, target);
  await fs.promises.writeFile(file, code, "utf8");

  const python = pythonFromRatRuntime(ratRuntime) ?? detectProjectPython(cwd);

  return {
    path: file,
    code,
    cwd,
    env: pythonDebugEnv(document, cwd, python, ratRuntime?.env),
    python,
  };
}

function buildRunnerCode(
  document: vscode.TextDocument,
  cells: CodeCell[],
  target: PythonDebugTarget,
): string {
  const source = document.uri.scheme === "file" ? document.uri.fsPath : document.uri.toString();
  const lines: string[] = [
    "# Auto-generated by Rat for VS Code Python debugging.",
    `# Source: ${source}`,
    `# Target: ${target}`,
    "# This temporary file is created so debugpy can launch the cell code.",
    "",
  ];

  cells.forEach((cell, index) => {
    lines.push(
      `# %% Rat cell ${index + 1}/${cells.length}: ${path.basename(document.fileName)}:${cell.openLine + 1}-${cell.closeLine + 1}`,
      cell.code,
      "",
    );
  });

  return lines.join("\n");
}

async function launchRunner(
  document: vscode.TextDocument,
  runner: RunnerInfo,
  target: PythonDebugTarget,
  cellCount: number,
): Promise<void> {
  const folder = vscode.workspace.getWorkspaceFolder(document.uri);
  const label = target === "above"
    ? `Rat: Debug ${cellCount} Python Cells`
    : "Rat: Debug Python Cell";

  const cleanup = vscode.debug.onDidTerminateDebugSession((session) => {
    if (session.configuration?.__ratDebugFile !== runner.path) return;
    cleanup.dispose();
    void fs.promises.rm(runner.path, { force: true }).catch(() => undefined);
  });

  const baseConfig: vscode.DebugConfiguration = {
    name: label,
    type: "debugpy",
    request: "launch",
    program: runner.path,
    cwd: runner.cwd,
    console: "integratedTerminal",
    justMyCode: false,
    env: runner.env,
    __ratDebugFile: runner.path,
  };

  if (runner.python) {
    // The Python/debugpy adapter accepts `python`; older adapters also accept
    // `pythonPath`. Supplying both makes the generated cell use the project's
    // .venv instead of an unrelated globally selected interpreter.
    baseConfig.python = runner.python;
    baseConfig.pythonPath = runner.python;
  }

  const ok = await tryStartDebugging(folder, {
    ...baseConfig,
    type: "debugpy",
  });

  if (ok) return;

  const fallbackOk = await tryStartDebugging(folder, {
    ...baseConfig,
    type: "python",
  });

  if (!fallbackOk) {
    cleanup.dispose();
    await fs.promises.rm(runner.path, { force: true }).catch(() => undefined);
    vscode.window.showErrorMessage(
      "Rat: could not start the Python debugger. Make sure the VS Code Python extension is installed and enabled.",
    );
  }
}

async function tryStartDebugging(
  folder: vscode.WorkspaceFolder | undefined,
  config: vscode.DebugConfiguration,
): Promise<boolean> {
  try {
    return await vscode.debug.startDebugging(folder, config);
  } catch {
    return false;
  }
}

function pythonDebugEnv(
  document: vscode.TextDocument,
  cwd: string,
  python: string | undefined,
  runtimeEnv: Record<string, string> | undefined,
): Record<string, string> {
  const env: Record<string, string> = { ...(runtimeEnv ?? {}) };
  const paths = [cwd];
  if (document.uri.scheme === "file") {
    paths.push(path.dirname(document.uri.fsPath));
  }

  if (env.PYTHONPATH) paths.push(env.PYTHONPATH);
  const existing = process.env.PYTHONPATH;
  if (existing) paths.push(existing);
  env.PYTHONPATH = uniquePaths(paths).join(path.delimiter);

  const venv = python ? venvDirFromPython(python) : null;
  if (python && venv) {
    const binDir = path.dirname(python);
    env.VIRTUAL_ENV = venv;
    env.PATH = [binDir, env.PATH ?? process.env.PATH ?? ""].filter(Boolean).join(path.delimiter);
  }

  return env;
}

async function resolveRatPythonRuntime(
  document: vscode.TextDocument,
  cwd: string,
): Promise<ResolvedRuntimeInfo | null> {
  // Prefer the extension's selected runtime (manual override / front matter /
  // setting), then fall back to the canonical rat CLI project alias. If the
  // extension computed a not-yet-saved project name, the exact lookup may fail;
  // `py` lets the CLI run its own resolver and still returns the right venv.
  const preferred = resolveRuntime("py", document).name;
  const inputs = preferred === "py" ? ["py"] : [preferred, "py"];

  for (const input of inputs) {
    try {
      const resolved = await ratResolve(input, cwd, true);
      if (resolved.lang === "py") return resolved;
    } catch {
      // Older rat CLIs don't have `rat resolve`, or this exact runtime is new.
    }
  }

  return null;
}

function pythonFromRatRuntime(
  runtime: ResolvedRuntimeInfo | null,
): string | undefined {
  if (!runtime || runtime.lang !== "py") return undefined;
  if (runtime.runtime_path && fs.existsSync(runtime.runtime_path)) {
    return runtime.runtime_path;
  }
  if (runtime.venv) return venvPythonPath(runtime.venv);
  return undefined;
}

function detectProjectPython(cwd: string): string | undefined {
  const candidates = process.platform === "win32"
    ? [
      path.join(cwd, ".venv", "Scripts", "python.exe"),
      path.join(cwd, "venv", "Scripts", "python.exe"),
    ]
    : [
      path.join(cwd, ".venv", "bin", "python"),
      path.join(cwd, ".venv", "bin", "python3"),
      path.join(cwd, "venv", "bin", "python"),
      path.join(cwd, "venv", "bin", "python3"),
    ];

  return candidates.find((candidate) => fs.existsSync(candidate));
}

function venvPythonPath(venv: string): string | undefined {
  const candidates = process.platform === "win32"
    ? [path.join(venv, "Scripts", "python.exe")]
    : [path.join(venv, "bin", "python"), path.join(venv, "bin", "python3")];
  return candidates.find((candidate) => fs.existsSync(candidate));
}

function venvDirFromPython(python: string): string | null {
  const binDir = path.dirname(python);
  const venv = path.dirname(binDir);
  const marker = path.join(venv, "pyvenv.cfg");
  return fs.existsSync(marker) ? venv : null;
}

function workspaceCwd(document: vscode.TextDocument): string {
  const folder = vscode.workspace.getWorkspaceFolder(document.uri);
  if (folder) return folder.uri.fsPath;
  if (document.uri.scheme === "file") return path.dirname(document.uri.fsPath);
  return process.cwd();
}

function uniquePaths(values: string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const value of values) {
    if (!value) continue;
    for (const part of value.split(path.delimiter)) {
      const trimmed = part.trim();
      if (!trimmed || seen.has(trimmed)) continue;
      seen.add(trimmed);
      result.push(trimmed);
    }
  }
  return result;
}

function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40) || "notebook";
}
